language: clojure
sudo: false
script: ./boot travis
branches:
  only:
    - master
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database mpg_test;' -U postgres
  - psql -d mpg_test -c 'create extension hstore;' -U postgres
  - psql -d mpg_test -c 'create extension citext;' -U postgres
jdk:
  - oraclejdk8
# travis does not support any of these (yet):
#  - oraclejdk9
#  - openjdk8
#  - openjdk9
install:
  - curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
  - chmod 755 boot
