language: clojure
sudo: false
script: lein test
branches:
  only:
    - master
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database mpg_test;' -U postgres
  - psql -d mpg_test -c 'create extension hstore;' -U postgres
  - psql -d mpg_test -c 'create extension citext;' -U postgres
jdk:
  - oraclejdk8
#  - openjdk7 # tests fail - probably running out of memory or disk
# travis does not support any of these (yet):
#  - oraclejdk9
#  - openjdk8
#  - openjdk9
